/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Skin
         * @description Analyze skin pixels and recommend foundations.
         *
         *     Accepts pre-extracted skin ROI pixels (RGB 0-255) from the frontend,
         *     along with optional color checker patches for calibration.
         */
        post: operations["analyze_skin_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Foundations */
        get: operations["list_foundations_foundations_get"];
        put?: never;
        /** Create Foundation */
        post: operations["create_foundation_foundations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundations/analyze-swatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyze Swatch
         * @description Analyze a foundation swatch photo and return extracted color values.
         *
         *     Upload a photo of foundation applied on white paper, optionally with
         *     ColorChecker patches for calibration. Returns LAB values, hex color,
         *     without saving to the database.
         */
        post: operations["analyze_swatch_foundations_analyze_swatch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundations/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Brands */
        get: operations["list_brands_foundations_brands_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundations/from-photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create Foundation From Photo
         * @description Analyze a foundation swatch photo and save the result to the database.
         *
         *     Same analysis as analyze-swatch, but also creates a Foundation record
         *     and stores the uploaded image.
         */
        post: operations["create_foundation_from_photo_foundations_from_photo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundations/storage-cleanups/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Storage Cleanups */
        post: operations["retry_storage_cleanups_foundations_storage_cleanups_retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/foundations/{foundation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Foundation */
        get: operations["get_foundation_foundations__foundation_id__get"];
        /** Update Foundation */
        put: operations["update_foundation_foundations__foundation_id__put"];
        post?: never;
        /** Delete Foundation */
        delete: operations["delete_foundation_foundations__foundation_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recommend From Skin Lab
         * @description Recommend foundations for an already computed skin LAB value.
         */
        post: operations["recommend_from_skin_lab_recommendations_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisConfidence */
        AnalysisConfidence: {
            /** Level */
            level: string;
            /** Notes */
            notes: string[];
            /** Score */
            score: number;
        };
        /** AnalysisMeta */
        AnalysisMeta: {
            confidence: components["schemas"]["AnalysisConfidence"];
            /** Fallback Used */
            fallback_used: boolean;
            /** Max Region Delta E */
            max_region_delta_e?: number | null;
            /** Method */
            method: string;
            /** Region Pixel Counts */
            region_pixel_counts: {
                [key: string]: number;
            };
            /** Total Pixel Count */
            total_pixel_count: number;
            /** Valid Region Count */
            valid_region_count: number;
        };
        /**
         * AnalysisRequest
         * @description Skin analysis request with color-checker calibrated pixels.
         */
        AnalysisRequest: {
            /** Brands */
            brands?: string[] | null;
            /** Checker Patches */
            checker_patches?: components["schemas"]["ColorCheckerPatch"][] | null;
            /** Product Names */
            product_names?: string[] | null;
            /** Skin Pixels Rgb */
            skin_pixels_rgb?: number[][] | null;
            skin_regions_rgb?: components["schemas"]["SkinRegionPixels"] | null;
            /**
             * Top N
             * @default 5
             */
            top_n: number;
        };
        /** AnalysisResponse */
        AnalysisResponse: {
            analysis_meta: components["schemas"]["AnalysisMeta"];
            /** Correction Applied */
            correction_applied: boolean;
            /** Recommendations */
            recommendations: components["schemas"]["RecommendationItem"][];
            /** Skin Hex */
            skin_hex: string;
            /** Skin Hex Raw */
            skin_hex_raw: string;
            /** Skin Lab */
            skin_lab: number[];
            /** Skin Lab Raw */
            skin_lab_raw: number[];
        };
        /** Body_analyze_swatch_foundations_analyze_swatch_post */
        Body_analyze_swatch_foundations_analyze_swatch_post: {
            /** Checker Patches */
            checker_patches?: string | null;
            /**
             * Image
             * Format: binary
             */
            image: string;
        };
        /** Body_create_foundation_from_photo_foundations_from_photo_post */
        Body_create_foundation_from_photo_foundations_from_photo_post: {
            /** Analysis Result */
            analysis_result?: string | null;
            /** Brand */
            brand: string;
            /** Checker Patches */
            checker_patches?: string | null;
            /**
             * Image
             * Format: binary
             */
            image: string;
            /** Product Name */
            product_name: string;
            /**
             * Shade Code
             * @default
             */
            shade_code: string;
            /** Shade Name */
            shade_name: string;
        };
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Client Id */
            client_id?: string | null;
            /** Client Secret */
            client_secret?: string | null;
            /** Grant Type */
            grant_type?: string | null;
            /** Password */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Username */
            username: string;
        };
        /** ColorCheckerDetectionResult */
        ColorCheckerDetectionResult: {
            /** Confidence */
            confidence: number;
            fiducials: components["schemas"]["ColorCheckerFiducials"];
            /** Patches */
            patches: components["schemas"]["DetectedColorCheckerPatch"][];
            /** Polygon */
            polygon: components["schemas"]["DetectionPoint"][];
            /** Score */
            score: number;
        };
        /** ColorCheckerFiducials */
        ColorCheckerFiducials: {
            center?: components["schemas"]["DetectionPoint"] | null;
            /** Corners */
            corners: components["schemas"]["DetectionPoint"][];
        };
        /**
         * ColorCheckerPatch
         * @description Measured RGB of a known color checker patch.
         */
        ColorCheckerPatch: {
            /** Measured Rgb */
            measured_rgb: number[];
            /** Reference Lab */
            reference_lab: number[];
        };
        /** DetectedColorCheckerPatch */
        DetectedColorCheckerPatch: {
            center: components["schemas"]["DetectionPoint"];
            /** Measured Rgb */
            measured_rgb: number[];
            /** Patch Index */
            patch_index: number;
            /** Polygon */
            polygon: components["schemas"]["DetectionPoint"][];
        };
        /** DetectionPoint */
        DetectionPoint: {
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** FoundationAnalysisConfidence */
        FoundationAnalysisConfidence: {
            /** Level */
            level: string;
            /** Notes */
            notes: string[];
            /** Score */
            score: number;
        };
        /** FoundationAnalysisResult */
        FoundationAnalysisResult: {
            /** L Value */
            L_value: number;
            /** A Value */
            a_value: number;
            /** B Value */
            b_value: number;
            confidence?: components["schemas"]["FoundationAnalysisConfidence"] | null;
            detection?: components["schemas"]["FoundationDetectionResult"] | null;
            /** Hex Color */
            hex_color: string;
            /** Undertone */
            undertone?: string | null;
        };
        /** FoundationCreate */
        FoundationCreate: {
            /** L Value */
            L_value: number;
            /** A Value */
            a_value: number;
            /** B Value */
            b_value: number;
            /** Brand */
            brand: string;
            /**
             * Hex Color
             * @default #000000
             */
            hex_color: string;
            /** Product Name */
            product_name: string;
            /**
             * Shade Code
             * @default
             */
            shade_code: string;
            /** Shade Name */
            shade_name: string;
            /** Swatch Image Url */
            swatch_image_url?: string | null;
            /** Undertone */
            undertone?: string | null;
        };
        /** FoundationDeleteResult */
        FoundationDeleteResult: {
            /** Ok */
            ok: boolean;
            /** Storage Cleanup */
            storage_cleanup: string;
        };
        /** FoundationDetectionResult */
        FoundationDetectionResult: {
            color_checker?: components["schemas"]["ColorCheckerDetectionResult"] | null;
            /** Color Correction Applied */
            color_correction_applied: boolean;
            /** Color Correction Source */
            color_correction_source?: string | null;
            swatch?: components["schemas"]["SwatchDetectionResult"] | null;
        };
        /** FoundationOut */
        FoundationOut: {
            /** L Value */
            L_value: number;
            /** A Value */
            a_value: number;
            /** B Value */
            b_value: number;
            /** Brand */
            brand: string;
            /** Hex Color */
            hex_color: string;
            /** Id */
            id: number;
            /** Product Name */
            product_name: string;
            /** Shade Code */
            shade_code: string;
            /** Shade Name */
            shade_name: string;
            /** Swatch Image Url */
            swatch_image_url: string | null;
            /** Undertone */
            undertone: string | null;
        };
        /** FoundationUpdate */
        FoundationUpdate: {
            /** L Value */
            L_value?: number | null;
            /** A Value */
            a_value?: number | null;
            /** B Value */
            b_value?: number | null;
            /** Brand */
            brand?: string | null;
            /** Hex Color */
            hex_color?: string | null;
            /** Product Name */
            product_name?: string | null;
            /** Shade Code */
            shade_code?: string | null;
            /** Shade Name */
            shade_name?: string | null;
            /** Swatch Image Url */
            swatch_image_url?: string | null;
            /** Undertone */
            undertone?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** RecommendationItem */
        RecommendationItem: {
            /** Brand */
            brand: string;
            /** Delta E */
            delta_e: number;
            /** Delta E Category */
            delta_e_category: string;
            /** Delta E Description */
            delta_e_description: string;
            /** Delta E Range */
            delta_e_range: string;
            /** Hex Color */
            hex_color: string;
            /** Id */
            id: number;
            /** Lab */
            lab: number[];
            /** Product Name */
            product_name: string;
            /** Shade Code */
            shade_code: string;
            /** Shade Name */
            shade_name: string;
            /** Undertone */
            undertone: string | null;
        };
        /**
         * RecommendationRequest
         * @description Recommendation-only request using an already analyzed skin LAB value.
         */
        RecommendationRequest: {
            /** Brands */
            brands?: string[] | null;
            /** Product Names */
            product_names?: string[] | null;
            /** Skin Lab */
            skin_lab: number[];
            /**
             * Top N
             * @default 200
             */
            top_n: number;
        };
        /**
         * SkinRegionPixels
         * @description Grouped facial skin pixels sampled from named ROI regions.
         */
        SkinRegionPixels: {
            /** Below Lips */
            below_lips?: number[][];
            /** Chin */
            chin?: number[][];
            /** Lower Left Cheek */
            lower_left_cheek?: number[][];
            /** Lower Right Cheek */
            lower_right_cheek?: number[][];
        };
        /** StorageCleanupRetryResult */
        StorageCleanupRetryResult: {
            /** Completed */
            completed: number;
            /** Pending */
            pending: number;
            /** Processed */
            processed: number;
        };
        /** SwatchDetectionResult */
        SwatchDetectionResult: {
            /** Pixel Count */
            pixel_count: number;
            /** Polygon */
            polygon: components["schemas"]["DetectionPoint"][];
            /** Raw Pixel Count */
            raw_pixel_count: number;
            /** Sample Hex */
            sample_hex: string;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    analyze_skin_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalysisRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_foundations_foundations_get: {
        parameters: {
            query?: {
                brand?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_foundation_foundations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoundationCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_swatch_foundations_analyze_swatch_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_swatch_foundations_analyze_swatch_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationAnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_brands_foundations_brands_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    create_foundation_from_photo_foundations_from_photo_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_foundation_from_photo_foundations_from_photo_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_storage_cleanups_foundations_storage_cleanups_retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StorageCleanupRetryResult"];
                };
            };
        };
    };
    get_foundation_foundations__foundation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                foundation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_foundation_foundations__foundation_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                foundation_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoundationUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_foundation_foundations__foundation_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                foundation_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoundationDeleteResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recommend_from_skin_lab_recommendations_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecommendationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
