create table if not exists public.foundations (
    id integer generated by default as identity primary key,
    brand varchar(100) not null,
    product_name varchar(200) not null default '',
    shade_code varchar(50) not null default '',
    shade_name varchar(100) not null,
    "L_value" double precision not null,
    "a_value" double precision not null,
    "b_value" double precision not null,
    hex_color varchar(7) not null default '#000000',
    undertone varchar(20),
    swatch_image_url varchar(500),
    created_at timestamptz not null default now()
);

create index if not exists ix_foundations_brand on public.foundations (brand);

alter table public.foundations enable row level security;
revoke all on table public.foundations from anon, authenticated;
revoke all on sequence public.foundations_id_seq from anon, authenticated;

update public.foundations
set undertone = null
where undertone is not null;

create table if not exists public.storage_cleanup_jobs (
    id bigint generated by default as identity primary key,
    bucket varchar(63) not null,
    object_path varchar(1024) not null,
    reason varchar(50) not null,
    attempts integer not null default 0 check (attempts >= 0),
    last_error text,
    created_at timestamptz not null default now(),
    completed_at timestamptz,
    constraint uq_storage_cleanup_asset unique (bucket, object_path)
);

create index if not exists ix_storage_cleanup_pending
    on public.storage_cleanup_jobs (created_at, id)
    where completed_at is null;

alter table public.storage_cleanup_jobs enable row level security;
revoke all on table public.storage_cleanup_jobs from anon, authenticated;
revoke all on sequence public.storage_cleanup_jobs_id_seq from anon, authenticated;

comment on table public.storage_cleanup_jobs is
    'Transactional outbox for idempotent Supabase Storage object cleanup.';
